### ISSUE TITLE
Please provide ESModule.

### ISSUE THREAD

**Issue by SaekiRaku** [sketch-hq/sketch-file-format-ts#21]
I'm using `Deno` to deal with sketch files, but it can't use require/export syntax of CommonJS.

**Comment by jedrichards** [comment]
Great idea. I'd be interested in what you're doing with Deno and Sketch files, will you have anything to show or is it private work? 🙂

**Comment by SaekiRaku** [comment]
Hi @jedrichards , I just starting that project, so I didn't have much to show, and I'm considering to use `Deno`. But even if not for `Deno`, an ESModule is still needy.

Anyway, my project is to generate Sketch Library for i18N purpose. I have developed a [Web UI library](https://qiqi-1996.github.io/qi-design-vue/) and provided the Sketch Library. The usage document of the library is doing i18n for developers, and I hope the Sketch Library can do i18n for designers too.

I know there has a `airbnb/react-sketchapp` can render React to Sketch, but it's lack of layout constraint currently. So it's not suitable for Sketch Library.

**Comment by jedrichards** [comment]
@SaekiRaku How does this look? https://github.com/sketch-hq/sketch-file-format-ts/pull/22

**Comment by jedrichards** [comment]
@SaekiRaku New version `5.1.0` - thanks for your input so far!
