### ISSUE TITLE
Layers are missing the `sharedObjectID` property

### ISSUE THREAD

**Issue by mathieudutour** [sketch-hq/sketch-file-format-ts#3]

**Comment by jedrichards** [comment]
Hey @mathieudutour ! ... I looked into this and `sharedObjectID` on styles was removed last year, quite a few document versions ago. What's your use case here? Would it make sense to add `sharedObjectID` as an optional property perhaps?

**Comment by mathieudutour** [comment]
Oh I forgot. It’s on the layer now IIRC. Never mind then (trying to update react-sketchapp to use the types, I opened issues for the things that didn’t match)

**Comment by mathieudutour** [comment]
Actually, layers are missing the `sharedStyleID` property

**Comment by jedrichards** [comment]
Aha literally just published `3.0.0` a few seconds ago, which should fix that I think. See how you get on.

**Comment by mathieudutour** [comment]
Hum I don't see anything, and `sketch-file-format` has no mention of `sharedStyleID`: https://github.com/sketch-hq/sketch-file-format/search?utf8=✓&q=sharedObjectID&type=

**Comment by mathieudutour** [comment]
also, will you fix the file format v1 and v2? I don't really want to generate files that only work for the latest version so I'm actually using `FileFormat1`

**Comment by jedrichards** [comment]
`sharedStyleID` on layers came in here https://github.com/sketch-hq/sketch-file-format/pull/26

And yeah, you're right I need to backport these fixes to the older versions too. Hopefully as the historical versions converge in terms of correctness I won't have to do this backporting too much.

**Comment by mathieudutour** [comment]
Ah my bad, I thought it was still called `sharedObjectID`
